### ISSUE TITLE
Can't find owner error

### ISSUE THREAD

**Issue by DRedDogPE** [Drowrin/Weeabot#1]
```python
bash-4.2$ python3.5 Weeabot.py
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "Weeabot.py", line 188, in on_ready
    await bot.update_owner()
  File "Weeabot.py", line 68, in update_owner
    self.owner = (await self.application_info()).owner
AttributeError: 'AppInfo' object has no attribute 'owner'```

**Comment by Drowrin** [comment]
Make sure you have the latest version of discord.py installed. AppInfo.owner was added in v0.11.0.
