### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by DRedDogPE** [Drowrin/Weeabot#2]
Erhhmm... after running the bot for a while i ran into this error

```python
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 102, in _default_help_command
    pages = bot.formatter.format_help_for(ctx, bot)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/formatter.py", line 280, in format_help_for
    return self.format()
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/formatter.py", line 325, in format
    data = sorted(self.filter_command_list(), key=category)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/formatter.py", line 244, in predicate
    return cmd.can_run(self.context)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 415, in can_run
    return all(predicate(context) for predicate in predicates)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 415, in <genexpr>
    return all(predicate(context) for predicate in predicates)
  File "/home/sakura/Weeabot/utils.py", line 13, in <lambda>
    return commands.check(lambda ctx: ctx.message.author.id == ctx.bot.owner.id)
AttributeError: 'NoneType' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "Weeabot.py", line 176, in on_command_error
    raise err
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 815, in process_commands
    yield from command.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 351, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 52, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by DRedDogPE** [comment]
```python
Ignoring exception in command_completion
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 247, in _run_extra
    yield from coro(*args, **kwargs)
  File "/home/sakura/Weeabot/cogs/profiles.py", line 105, in on_command_completion
    await self.inc_use(ctx.message.author.id, full_command_name(ctx, command))
  File "/home/sakura/Weeabot/cogs/profiles.py", line 97, in inc_use
    cc = self.get_field_by_id(uid, 'command_count')
  File "/home/sakura/Weeabot/cogs/profiles.py", line 67, in get_field_by_id
    up[key] = self.bot.defaults[key]
KeyError: 'command_count'
```

**Comment by Drowrin** [comment]
First case is you might have been trying to issue commands before the bot was ready.

Second is indeed a bug. I'll get on that.

**Comment by Drowrin** [comment]
Apologies for the delay. Commit for the fix will go up tonight.
